export const INITIAL_DEMO_USER = {
  id: "user-hero-001",
  email: "kidpoker@royalpoker.com",
  password: "password123",
  name: "Daniel 'KidPoker' Mercer",
  avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
  role: "High Stakes Pro",
  bankroll: 85000,
  preferredTheme: "emerald",
  preferredSimRuns: 10000,
  soundEffects: true,
};

export const INITIAL_OPPONENTS = [
  {
    id: "opp-001",
    userId: "user-hero-001",
    name: "Garrett 'The Shark' V.",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    archetype: "LAG",
    vpip: "32.5",
    pfr: "26.0",
    threeBet: "11.4",
    aggressionFactor: "4.2",
    foldToCbet: "32.0",
    wtsd: "29.5",
    notes: "Super aggressive on turns and rivers. Frequent triple-barrel bluffs when scare cards land. Folds reluctantly to check-raises.",
    exploits: JSON.stringify([
      "Call down lighter with 2nd pair top kicker on paired runouts",
      "Check-raise dry flops to stop aggressive probe bets",
      "Do not slow-play monsters against his aggressive river stabs"
    ]),
    colorTag: "rose",
    handsTracked: 1420,
  },
  {
    id: "opp-002",
    userId: "user-hero-001",
    name: "Nik 'Airball' K.",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    archetype: "Maniac",
    vpip: "54.0",
    pfr: "41.0",
    threeBet: "18.5",
    aggressionFactor: "5.8",
    foldToCbet: "21.0",
    wtsd: "38.0",
    notes: "Volatile hyper-aggressive whale. Shoves marginal draws and over-values bottom two pair. Tilts easily after losing a $20k pot.",
    exploits: JSON.stringify([
      "Widen value-betting range significantly",
      "Never bluff into him; he cannot fold pair+flush draws",
      "Trap with disguised sets and nut flushes"
    ]),
    colorTag: "amber",
    handsTracked: 890,
  },
  {
    id: "opp-003",
    userId: "user-hero-001",
    name: "Dan 'GTO Machine' S.",
    avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80",
    archetype: "GTO Wizard",
    vpip: "21.5",
    pfr: "18.0",
    threeBet: "8.2",
    aggressionFactor: "2.9",
    foldToCbet: "44.0",
    wtsd: "25.0",
    notes: "Balanced mixed strategy frequencies. Strong range protection and blocker awareness. Uses geometric bet sizing.",
    exploits: JSON.stringify([
      "Target his capped calling ranges on monotone runouts",
      "Avoid large bluff shoves without nut flush/straight blockers",
      "Exploit slight over-folding to small flop check-minraises"
    ]),
    colorTag: "cyan",
    handsTracked: 2600,
  },
  {
    id: "opp-004",
    userId: "user-hero-001",
    name: "Sammy 'The Rock' Miller",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
    archetype: "Nit",
    vpip: "12.0",
    pfr: "9.5",
    threeBet: "3.1",
    aggressionFactor: "1.4",
    foldToCbet: "68.0",
    wtsd: "19.0",
    notes: "Extreme rock. Only enters pot with JJ+, AK. If he raises your river bet, he ALWAYS has the nuts.",
    exploits: JSON.stringify([
      "Steal his blinds relentlessly with any two cards",
      "Fold immediately whenever he check-raises the turn or river",
      "C-bet 100% of flop textures against his check"
    ]),
    colorTag: "emerald",
    handsTracked: 740,
  },
];

export const INITIAL_SAVED_SCENARIOS = [
  {
    id: "scen-001",
    userId: "user-hero-001",
    title: "River Cooler Bluff Catch vs Garrett ($14,200 Pot)",
    gameType: "No-Limit Cash $25/$50",
    heroCards: JSON.stringify(["As", "Kd"]),
    boardCards: JSON.stringify(["Ks", "7d", "2c", "Qh", "Jc"]),
    opponentsData: JSON.stringify([
      { id: "opp-001", name: "Garrett 'The Shark' V.", cards: ["Qd", "Jd"] }
    ]),
    potSize: "14200",
    betToCall: "4800",
    street: "river",
    simulationRuns: 10000,
    heroEquity: "0.0",
    heroWinPct: "0.0",
    heroTiePct: "0.0",
    potOddsPct: "25.2",
    evChips: "-4800.0",
    recommendation: "FOLD (-EV)",
    notes: "Hero paired Kings top kicker, but opponent turned and rivered two pair (Queens and Jacks). Simulation confirms a clear fold against his polarized river barrel.",
  },
  {
    id: "scen-002",
    userId: "user-hero-001",
    title: "Nut Flush Draw + Overcards vs Airball Shove",
    gameType: "High Stakes $100/$200",
    heroCards: JSON.stringify(["Ah", "Kh"]),
    boardCards: JSON.stringify(["9h", "4h", "2c"]),
    opponentsData: JSON.stringify([
      { id: "opp-002", name: "Nik 'Airball' K.", cards: ["9s", "8s"] }
    ]),
    potSize: "36000",
    betToCall: "11000",
    street: "flop",
    simulationRuns: 15000,
    heroEquity: "52.8",
    heroWinPct: "52.4",
    heroTiePct: "0.8",
    potOddsPct: "19.0",
    evChips: "+13840.0",
    recommendation: "CALL / RAISE ALL-IN (+EV)",
    notes: "Hero holds Nut Flush draw plus two overcards (15 clean outs on the turn/river). Massively +EV call against top pair weak kicker.",
  },
  {
    id: "scen-003",
    userId: "user-hero-001",
    title: "Pocket Aces vs 3 Opponents Preflop 4-Bet",
    gameType: "WSOP Main Event MTT",
    heroCards: JSON.stringify(["Ah", "As"]),
    boardCards: JSON.stringify([]),
    opponentsData: JSON.stringify([
      { id: "opp-002", name: "Nik 'Airball' K.", cards: ["Kh", "Qh"] },
      { id: "opp-003", name: "Dan 'GTO Machine' S.", cards: ["Jc", "Jd"] }
    ]),
    potSize: "84000",
    betToCall: "22000",
    street: "preflop",
    simulationRuns: 20000,
    heroEquity: "73.2",
    heroWinPct: "72.8",
    heroTiePct: "0.8",
    potOddsPct: "17.2",
    evChips: "+39480.0",
    recommendation: "VALUE ALL-IN (+EV)",
    notes: "Pocket Aces multi-way preflop hold 73.2% equity against two aggressive opponents. Standard GTO 5-bet jam for maximum value.",
  },
];
